### PR TITLE
Cease using cryptographic hashes

### LINKED ISSUE #32: Key computing for Memcached leaks hashers
Both NHibernate-Caches MemCache and EnyimMemcached use a hash algorithm for computing keys when they exceed the maximal length supported by Memcached, 250.

They use a thread-static instance of `HashAlgorithm`, which is disposable. There is no way to properly dispose of them. They should be local variables instead.

Initially reported as:

~~Both NHibernate-Caches MemCache and EnyimMemcached use a non-thread safe algorithm for computing keys when they exceed the maximal length supported by Memcached, 250.~~

~~They use a static instance of `HashAlgorithm`, which is not thread safe. This may cause caching or retrieving values with unexpected keys. The `HashAlgorithm` instance must be a local variable of the function computing the key. (It cannot either be a non static field, since caches need to be thread safe.)~~ No thread safety issue, they are stored as `ThreadStatic` variables.

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Under Windows, cryptographic hash may be rejected if FIPS is enabled and the used algorithm is not FIPS compliant.

Fix #32 by the way

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
Or maybe still better, do not use cryptographic algorithms, as suggested by @hazzik [here](https://github.com/nhibernate/nhibernate-core/pull/1802#issuecomment-405394757) for another case.

Using a 32 bits stable hash in hex form would take 8 characters, which could replace part of the key for shortening too long ones, and should be quite good at avoiding collisions.

**Comment by fredericDelaporte** [comment]
Commit amended for using a simple stable hash algorithm instead of a cryptographic one when a key needs to be shortened.

Moreover now the hash will not fully replace the key, but the key will just be shortened to accommodate its max length (hash appended to it).

File: CommonInternals/Hasher.cs [hunk 1]
```diff
@@ -0,0 +1,117 @@
+/*
+ * Derived from MurmurHash2Simple,
+ * http://landman-code.blogspot.com/2009/02/c-superfasthash-and-murmurhash2.html
+ */
```
Comment (fredericDelaporte) [inline CommonInternals/Hasher.cs]: That is the same code than the one added in nhibernate/nhibernate-core#1802. Added a common library for sharing it among cache libraries was looking as an overkill, so I have added it as a common file.

File: CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs [hunk 2]
```diff
@@ -175,24 +174,18 @@ private static bool GetUseSlidingExpiration(IDictionary<string, string> props)
...
 				// Hash it for respecting max key size. Collisions will be avoided by storing the actual key along
 				// the object and comparing it on retrieval.
-				using (var hasher = new SHA256Managed())
+				var hash = Hasher.HashToString(keyAsString);
+				if (hash.Length > _maxKeySize)
 				{
-					var bytes = Encoding.UTF8.GetBytes(keyAsString);
-					var computedHash = Convert.ToBase64String(hasher.ComputeHash(bytes));
-					if (computedHash.Length <= _maxKeySize)
-						return computedHash;
```
Comment (fredericDelaporte) [inline CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs]: Unrelated bug fix by the way. In this case, if the hashed had to be sanitized, it would not have been sanitized.
